// Datos locales por comuna. Fuente única para las páginas
// /kinesiologo-a-domicilio-{comuna} y /{especialidad}-{comuna}.
// Cada comuna aporta sectores y contexto propio para evitar contenido duplicado.

export type ZonaComuna = "oriente" | "centro" | "norte" | "poniente" | "sur"

export interface Comuna {
    nombre: string
    slug: string
    /** Provincia de la Region Metropolitana */
    provincia: string
    /** Zona usada para enlazar comunas vecinas entre si */
    zona: ZonaComuna
    /** "full": hub + 5 paginas de especialidad. "hub": solo la pagina de la comuna. */
    cobertura: "full" | "hub"
    /** Solo para las comunas generadas: alimenta el meta description y el schema del hub */
    descripcion?: string
    /** Solo para las comunas generadas: bullets de cobertura del hub */
    caracteristicas?: string[]
    /** Sectores/barrios reales que se listan en la página */
    sectores: string[]
    /** Frase de contexto local, única por comuna */
    contexto: string
    /** Referencias geográficas que usan los vecinos para ubicarse */
    referencias: string
    /** Cuándo llega el kinesiólogo */
    llegada: string
}

export const comunas: Comuna[] = [
    {
        nombre: "Las Condes",
        slug: "las-condes",
        provincia: "Santiago",
        zona: "oriente",
        cobertura: "full",
        sectores: [
            "El Golf",
            "Escuela Militar",
            "Manquehue",
            "San Carlos de Apoquindo",
            "Estoril",
            "Los Dominicos",
            "Nueva Las Condes",
            "Cantagallo",
        ],
        contexto:
            "Las Condes concentra la mayor demanda de salud domiciliaria del sector oriente, con muchos pacientes que salen de clínicas cercanas y necesitan continuar su rehabilitación en casa.",
        referencias: "cerca de Apoquindo, Kennedy y el eje Escuela Militar–Los Dominicos",
        llegada: "el mismo día en la mayoría de los casos",
    },
    {
        nombre: "Vitacura",
        slug: "vitacura",
        provincia: "Santiago",
        zona: "oriente",
        cobertura: "full",
        sectores: [
            "Santa María de Manquehue",
            "Jardín del Este",
            "Lo Curro",
            "Vitacura Centro",
            "Alonso de Córdova",
            "Parque Bicentenario",
            "Tabancura",
        ],
        contexto:
            "Vitacura tiene una alta proporción de adultos mayores viviendo en casas amplias, un entorno ideal para rehabilitar sin trasladarse.",
        referencias: "cerca de Av. Vitacura, Kennedy y el Parque Bicentenario",
        llegada: "el mismo día en la mayoría de los casos",
    },
    {
        nombre: "Providencia",
        slug: "providencia",
        provincia: "Santiago",
        zona: "oriente",
        cobertura: "full",
        sectores: [
            "Pedro de Valdivia",
            "Manuel Montt",
            "Tobalaba",
            "Los Leones",
            "Salvador",
            "Bellavista",
            "Costanera Center",
            "Parque Bustamante",
        ],
        contexto:
            "En Providencia la mayoría de los pacientes vive en departamentos y trabaja en la misma comuna: subimos con camilla y equipamiento en horarios compatibles con la jornada laboral.",
        referencias: "cerca del eje Providencia–Nueva Providencia y las estaciones Salvador, Manuel Montt y Los Leones",
        llegada: "el mismo día en la mayoría de los casos",
    },
    {
        nombre: "Ñuñoa",
        slug: "nunoa",
        provincia: "Santiago",
        zona: "oriente",
        cobertura: "full",
        sectores: [
            "Plaza Ñuñoa",
            "Avenida Irarrázaval",
            "Simón Bolívar",
            "Parque Bustamante",
            "Villa Frei",
            "Barrio Italia",
            "Campus Oriente",
            "Estadio Nacional",
        ],
        contexto:
            "Ñuñoa mezcla casas antiguas y edificios nuevos, con muchas familias que cuidan a un adulto mayor en casa y agradecen no tener que trasladarlo.",
        referencias: "cerca de Plaza Ñuñoa, Irarrázaval y el Estadio Nacional",
        llegada: "el mismo día en la mayoría de los casos",
    },
    {
        nombre: "La Reina",
        slug: "la-reina",
        provincia: "Santiago",
        zona: "oriente",
        cobertura: "full",
        sectores: [
            "La Reina Alta",
            "Príncipe de Gales",
            "Avenida Ossa",
            "Plaza Egaña",
            "Larraín",
            "Parque Padre Hurtado",
            "Villa La Reina",
            "Talinay",
        ],
        contexto:
            "La Reina es tranquila y arbolada, con calles y parques que aprovechamos para la fase de marcha y reacondicionamiento al aire libre.",
        referencias: "cerca de Plaza Egaña, Av. Ossa y el Parque Padre Hurtado",
        llegada: "el mismo día en la mayoría de los casos",
    },
    {
        nombre: "Lo Barnechea",
        slug: "lo-barnechea",
        provincia: "Santiago",
        zona: "oriente",
        cobertura: "full",
        sectores: [
            "La Dehesa",
            "Los Trapenses",
            "El Arrayán",
            "Portal La Dehesa",
            "Cerro 18",
            "El Huinganal",
            "Santa Blanca",
            "La Ermita",
        ],
        contexto:
            "Lo Barnechea es la comuna más extensa de nuestra cobertura y la peor conectada con centros de rehabilitación: por eso la atención en casa marca la mayor diferencia, sin recargo por distancia.",
        referencias: "cerca de La Dehesa, Camino a Farellones y Los Trapenses",
        llegada: "coordinado con hora fija, sin recargo por subir",
    },
    {
        nombre: "Peñalolén",
        slug: "penalolen",
        provincia: "Santiago",
        zona: "oriente",
        cobertura: "full",
        sectores: [
            "Peñalolén Alto",
            "Comunidad Ecológica",
            "San Luis",
            "Lo Hermida",
            "Consistorial",
            "Avenida Grecia",
            "Quilín Oriente",
            "Peñalolén Nuevo",
        ],
        contexto:
            "Peñalolén tiene poca oferta de rehabilitación propia y sus vecinos suelen bajar a Ñuñoa o La Reina: nosotros subimos con todo el equipamiento, incluida la zona precordillera.",
        referencias: "cerca de Av. Grecia, Tobalaba sur y la Comunidad Ecológica",
        llegada: "coordinado con hora fija, sin recargo por subir",
    },
    {
        nombre: "La Florida",
        slug: "la-florida",
        provincia: "Santiago",
        zona: "sur",
        cobertura: "full",
        sectores: [
            "Bellavista de La Florida",
            "Walker Martínez",
            "Trinidad",
            "Los Quillayes",
            "Rojas Magallanes",
            "Santa Raquel",
            "Gerónimo de Alderete",
            "La Florida Alto",
        ],
        contexto:
            "La Florida es una de las comunas más pobladas de Santiago y sus centros de rehabilitación están siempre copados: con atención domiciliaria partes el tratamiento esta misma semana, con hora fija.",
        referencias: "cerca de Vicuña Mackenna, Walker Martínez y Bellavista de La Florida",
        llegada: "el mismo día o al día siguiente",
    },
    {
        nombre: "Macul",
        slug: "macul",
        provincia: "Santiago",
        zona: "oriente",
        cobertura: "full",
        sectores: [
            "Villa Macul",
            "Quilín",
            "Santa Julia",
            "Rodrigo de Araya",
            "Macul Centro",
            "Los Presidentes",
            "Eje Vicuña Mackenna",
            "Campus San Joaquín",
        ],
        contexto:
            "Macul combina barrios residenciales consolidados con muchos adultos mayores que viven solos o con su familia: llevamos la rehabilitación completa a su living.",
        referencias: "cerca de Vicuña Mackenna, Quilín y Departamental",
        llegada: "el mismo día o al día siguiente",
    },
    {
        nombre: "San Joaquín",
        slug: "san-joaquin",
        provincia: "Santiago",
        zona: "centro",
        cobertura: "full",
        sectores: [
            "Metro San Joaquín",
            "Pedrero",
            "La Castrina",
            "El Pinar",
            "Eje Santa Rosa",
            "Eje Vicuña Mackenna",
            "Campus San Joaquín",
            "Barrio Aníbal Pinto",
        ],
        contexto:
            "San Joaquín casi no tiene centros de rehabilitación propios y sus vecinos terminan viajando a otras comunas: el kinesiólogo llega con camilla y equipamiento completo a la puerta.",
        referencias: "cerca de Santa Rosa, Vicuña Mackenna y las estaciones Pedrero y San Joaquín",
        llegada: "el mismo día o al día siguiente",
    },
    {
        nombre: "Santiago Centro",
        slug: "santiago-centro",
        provincia: "Santiago",
        zona: "centro",
        cobertura: "full",
        sectores: [
            "Barrio Lastarria",
            "Barrio Brasil",
            "Barrio Yungay",
            "Barrio República",
            "Parque Almagro",
            "Barrio Matta",
            "Santa Ana",
            "Parque Forestal",
        ],
        contexto:
            "En Santiago Centro la mayoría vive en departamentos y depende del metro: subimos a tu piso con todo el equipamiento y en horarios que calzan con el trabajo.",
        referencias: "cerca de la Alameda, el Parque Forestal y los barrios Lastarria, Brasil y Yungay",
        llegada: "el mismo día en la mayoría de los casos",
    },
    {
        nombre: "La Pintana",
        slug: "la-pintana",
        provincia: "Santiago",
        zona: "sur",
        cobertura: "full",
        descripcion: "Kinesiología a domicilio en La Pintana: sesiones en tu casa en El Castillo, Santo Tomás, San Rafael y el resto de la comuna, con evaluación inicial gratuita y atención de lunes a domingo.",
        caracteristicas: [
            "Comuna en ampliación de cobertura: la primera visita se coordina según la agenda del equipo",
            "El kinesiólogo llega en vehículo con camilla y equipamiento, porque la comuna aún no tiene estación de Metro en operación",
            "Evaluación inicial gratuita en tu casa, sin costo ni compromiso",
            "Atención de lunes a domingo, con sesiones de alrededor de 60 minutos",
            "Servicio particular con boleta de honorarios electrónica, reembolsable en tu Isapre o seguro complementario según la cobertura de tu plan",
            "Trabajo adaptado a casas pareadas y a blocks de tres o cuatro pisos sin ascensor",
        ],
        sectores: [
            "El Castillo",
            "Santo Tomás",
            "El Roble",
            "San Rafael",
            "Pablo de Rokha",
            "Santiago de Nueva Extremadura",
            "Villa La Pintana",
            "Mapuhue",
        ],
        contexto: "La Pintana está en el extremo sur del Gran Santiago y toda su red de salud local es primaria: los controles hospitalarios y la rehabilitación de alta complejidad quedan fuera de la comuna. Recibir al kinesiólogo en casa evita justamente el viaje que más cuesta hacer cuando moverse duele.",
        referencias: "cerca de Avenida Santa Rosa, el cruce con Avenida Gabriela y los ejes Lo Blanco y Observatorio",
        llegada: "coordinamos la visita según la agenda del equipo, habitualmente dentro de 24 a 48 horas",
    },
    {
        nombre: "Puente Alto",
        slug: "puente-alto",
        provincia: "Cordillera",
        zona: "sur",
        cobertura: "full",
        descripcion: "Kinesiología a domicilio en Puente Alto, de Bajos de Mena al sector precordillerano de Las Vizcachas. Evaluación inicial gratuita, sesiones de unos 60 minutos y atención de lunes a domingo.",
        caracteristicas: [
            "Atendemos por sector: centro y Plaza de Puente Alto, Gabriela Oriente y Poniente, Bajos de Mena, El Volcán, Casas Viejas, San Gerónimo y el sector precordillerano de Las Vizcachas y El Peral.",
            "El kinesiólogo sube camilla y equipamiento por la escalera en los blocks sin ascensor de Bajos de Mena, El Volcán y Villa Pedro Lira.",
            "Si vives en condominio cerrado o en parcela con portón, coordinamos el ingreso antes de la visita para no perder minutos de sesión.",
            "Evaluación inicial gratuita y sesiones de unos 60 minutos, de lunes a domingo, con hora convenida.",
            "Servicio particular con boleta de honorarios electrónica, reembolsable en tu Isapre o seguro complementario según la cobertura de tu plan.",
            "Por la distancia dentro de la comuna, la primera visita se coordina habitualmente dentro de 24 a 48 horas, según agenda.",
        ],
        sectores: [
            "Sector centro / Plaza de Puente Alto",
            "Bajos de Mena",
            "El Volcán",
            "Casas Viejas",
            "San Gerónimo",
            "Gabriela Oriente",
            "Gabriela Poniente",
            "Las Vizcachas",
        ],
        contexto: "Puente Alto es una comuna extensa y las distancias dentro de ella son largas: entre un block de Bajos de Mena y una parcela de Las Vizcachas hay realidades muy distintas, así que agendamos por sector y con hora convenida. El kinesiólogo llega igual con camilla y equipamiento, suba por escalera o entre por un camino interior.",
        referencias: "cerca de Av. Concha y Toro, Av. Gabriela y el terminal del Metro Línea 4 en Plaza de Puente Alto",
        llegada: "coordinamos la visita según agenda y sector, habitualmente dentro de 24 a 48 horas",
    },
    {
        nombre: "Pudahuel",
        slug: "pudahuel",
        provincia: "Santiago",
        zona: "poniente",
        cobertura: "full",
        descripcion: "Kinesiología a domicilio en Pudahuel, en Pudahuel Norte y Sur, Barrancas, La Estrella y Laguna Sur. Evaluación inicial gratuita, sesiones de alrededor de 60 minutos y atención de lunes a domingo.",
        caracteristicas: [
            "Atendemos el sector urbano: Pudahuel Norte y Sur, Barrancas, La Estrella y Laguna Sur",
            "En Ciudad de Los Valles, Lomas de Lo Aguirre y El Noviciado confirmamos disponibilidad al agendar; por los caminos del poniente te pedimos una referencia del acceso, porque la numeración no siempre orienta",
            "Preguntamos el piso y si el edificio tiene ascensor antes de la visita, por los blocks de Pudahuel Sur",
            "En condominios con conserjería conviene dejar avisado en portería el nombre del kinesiólogo",
            "Atención de lunes a domingo, útil si trabajas por turnos en el aeropuerto o en Enea",
            "Servicio particular: boleta de honorarios electrónica para pedir reembolso en tu Isapre o seguro complementario, según tu plan",
        ],
        sectores: [
            "Pudahuel Norte",
            "Pudahuel Sur",
            "Barrancas",
            "La Estrella",
            "Laguna Sur",
            "Ciudad de Los Valles",
            "Lomas de Lo Aguirre",
            "El Noviciado",
        ],
        contexto: "Pudahuel está partida en dos por el aeropuerto y la Ruta 68: por un lado el sector urbano de Pudahuel Norte y Sur, por otro los condominios y el campo del poniente. Esa distancia interna es la que vuelve incómodo cualquier tratamiento que obligue a salir tres veces por semana.",
        referencias: "cerca de Av. San Pablo, Av. Américo Vespucio y las estaciones Pudahuel, Barrancas y Laguna Sur de la Línea 5",
        llegada: "coordinamos la visita según agenda, habitualmente dentro de 24 a 48 horas",
    },
    {
        nombre: "Maipú",
        slug: "maipu",
        provincia: "Santiago",
        zona: "poniente",
        cobertura: "full",
        descripcion: "Kinesiología a domicilio en Maipú: Maipú Centro, Ciudad Satélite, El Abrazo, Portal del Sol, Sol Poniente y las parcelas de Rinconada. Evaluación inicial gratuita, sesiones de unos 60 minutos y atención de lunes a domingo.",
        caracteristicas: [
            "Cobertura de Maipú Centro, Ciudad Satélite, El Abrazo, Portal del Sol, Sol Poniente, Los Héroes, Lo Errázuriz y Rinconada",
            "Evaluación inicial gratuita en tu casa, coordinando la dirección exacta y una referencia del acceso",
            "Hora fija acordada, de lunes a domingo: el mismo día o al día siguiente en el área urbana, y dentro de 24 a 48 horas en Rinconada",
            "Sesiones de unos 60 minutos con camilla y equipamiento portátil, sin cruzar la comuna por Pajaritos o 5 de Abril para cada atención",
            "Continuidad de la rehabilitación tras un alta hospitalaria, siguiendo la epicrisis y las indicaciones de tu médico",
            "Boleta de honorarios electrónica para pedir reembolso en tu Isapre o seguro complementario, según tu plan",
        ],
        sectores: [
            "Maipú Centro",
            "Ciudad Satélite",
            "El Abrazo",
            "Portal del Sol",
            "Sol Poniente",
            "Los Héroes",
            "Lo Errázuriz",
            "Rinconada",
        ],
        contexto: "Maipú es de las comunas más extensas de Santiago y solo una parte de su territorio está urbanizada, así que cruzarla de un extremo a otro toma más de lo que uno calcula, aunque el centro de Santiago quede a unos 13 kilómetros por la Ruta 78. Por eso acordamos hora fija y llegamos con camilla y equipamiento, desde las villas de Maipú Centro hasta las parcelas de Rinconada.",
        referencias: "cerca de Av. Pajaritos y la Plaza de Maipú, con el Templo Votivo, el eje 5 de Abril y las estaciones de la Línea 5 como puntos de encuentro",
        llegada: "el mismo día o al día siguiente en el área urbana; en Rinconada coordinamos según agenda, habitualmente dentro de 24 a 48 horas",
    },
    {
        nombre: "San Bernardo",
        slug: "san-bernardo",
        provincia: "Maipo",
        zona: "sur",
        cobertura: "full",
        descripcion: "Kinesiología a domicilio en San Bernardo, del casco histórico al Barrio Estación, Nos y Lo Herrera. Evaluación inicial gratuita, sesiones de unos 60 minutos y atención de lunes a domingo.",
        caracteristicas: [
            "Cubrimos el casco histórico, el Barrio Estación y la Maestranza, Cinco Pinos, Los Morros, El Manzano, Tejas de Chena y Nos.",
            "Llegamos también al tramo semirrural de Lo Herrera, La Vara y El Mariscal, con parcelas y caseríos alejados del centro comunal.",
            "En las casonas del casco histórico solemos aprovechar el pasillo para entrenar la marcha; en los blocks de vivienda social sin ascensor el kinesiólogo sube con el equipamiento y se trabaja en el dormitorio o el comedor.",
            "Al agendar conviene dar una referencia del acceso, como el portón, el número de parcela o el paradero más cercano, sobre todo en los sectores lejos del centro.",
            "Servicio particular con boleta de honorarios electrónica, reembolsable en tu Isapre o seguro complementario según tu plan.",
            "Sin convenio con hospitales ni clínicas: lo que define el plan son las indicaciones de tu médico tratante.",
        ],
        sectores: [
            "Centro de San Bernardo (Plaza de Armas)",
            "Barrio Estación / Maestranza",
            "Nos",
            "Cinco Pinos",
            "Los Morros",
            "El Manzano",
            "Tejas de Chena",
            "Lo Herrera",
        ],
        contexto: "San Bernardo se estira desde el casco histórico de la Plaza de Armas hasta Nos, Lo Herrera y La Vara, donde ya aparecen parcelas y caseríos. Quien necesita rehabilitarse varias veces por semana termina cruzando la comuna entera, y llevar las sesiones a la casa es justamente lo que evita ese recorrido.",
        referencias: "cerca de la Plaza de Armas, Eyzaguirre, el eje Gran Avenida y las estaciones del tren Nos–Estación Central",
        llegada: "coordinamos la visita según agenda, habitualmente dentro de 24 a 48 horas, agrupando las sesiones por sector y con hora fija",
    },
    {
        nombre: "Quilicura",
        slug: "quilicura",
        provincia: "Santiago",
        zona: "norte",
        cobertura: "full",
        descripcion: "Kinesiología a domicilio en Quilicura, de Quilicura Centro a Valle Lo Campino, Altos de Quilicura y Santa Luisa: el kinesiólogo llega con camilla y equipamiento a tu casa o departamento, sin que tengas que cruzar la comuna ni salir a la red norte por cada sesión. Servicio particular, con evaluación inicial gratuita y atención de lunes a domingo.",
        caracteristicas: [
            "Cubrimos Quilicura Centro, Valle Lo Campino, Altos y Lomas de Quilicura, Santa Luisa, Ciudad Nueva, Parque Real y El Mañío",
            "El cordón industrial y logístico de Américo Vespucio y la Ruta 5 separa los barrios entre sí: en vez de cruzar la comuna para cada sesión, el kinesiólogo llega a tu dirección",
            "En los blocks y edificios de hasta cinco pisos que no tienen ascensor, la camilla y el equipamiento suben por la escalera: avísanos el piso al coordinar",
            "Comuna incorporada en la ampliación a la Región Metropolitana: la primera visita se coordina según agenda, habitualmente dentro de 24 a 48 horas",
            "Atención de lunes a domingo, con sesiones de alrededor de 60 minutos y evaluación inicial gratuita",
            "Servicio particular con boleta de honorarios electrónica, reembolsable en tu isapre o seguro complementario según la cobertura de tu plan; KINEUM no tiene convenio con los CESFAM, SAPU ni hospitales nombrados en esta página",
        ],
        sectores: [
            "Quilicura Centro",
            "Valle Lo Campino",
            "Altos de Quilicura",
            "Lomas de Quilicura",
            "Santa Luisa",
            "Ciudad Nueva",
            "Parque Real",
            "El Mañío",
        ],
        contexto: "Quilicura quedó partida por el cordón industrial y logístico de Américo Vespucio y la Ruta 5: sus barrios residenciales están separados unos de otros y lo de mayor complejidad se atiende fuera, en la red norte. Atenderse en casa evita esos desplazamientos justo cuando moverse cuesta.",
        referencias: "cerca de Av. Bernardo O'Higgins y el Mall Arauco, el centro histórico en torno a Av. Arturo Prat y las estaciones Ferrocarril, Lo Cruzat y Plaza de Quilicura de la Línea 3",
        llegada: "según agenda, habitualmente dentro de 24 a 48 horas",
    },
    {
        nombre: "Huechuraba",
        slug: "huechuraba",
        provincia: "Santiago",
        zona: "norte",
        cobertura: "full",
        descripcion: "Kinesiología a domicilio en Huechuraba, de La Pincoya y El Barrero a Pedro Fontova, Santa Marta y Ciudad Empresarial. Evaluación inicial gratuita y boleta de honorarios electrónica reembolsable en tu Isapre o seguro complementario, según tu plan.",
        caracteristicas: [
            "Cobertura en La Pincoya, El Barrero, Los Libertadores, Pedro Fontova, El Carmen, Santa Marta, Bosques de la Pirámide y Ciudad Empresarial",
            "Subimos con camilla y equipamiento a blocks sin ascensor: avísanos el piso y si hay escalera al coordinar",
            "Entrada a condominios y torres con conserjería: dejamos el nombre del kinesiólogo para la portería",
            "Atención de lunes a domingo, con hora fija coordinada por WhatsApp al +56 9 9967 9593",
            "Evaluación inicial gratuita y sesiones de alrededor de 60 minutos en tu casa",
            "Servicio particular, sin convenio con hospitales ni clínicas: boleta de honorarios electrónica reembolsable en Isapre o seguro complementario, según tu plan",
        ],
        sectores: [
            "La Pincoya",
            "El Barrero",
            "Villa Los Libertadores",
            "Ciudad Empresarial",
            "Pedro Fontova Norte",
            "El Carmen de Huechuraba",
            "Santa Marta de Huechuraba",
            "Bosques de la Pirámide",
        ],
        contexto: "Huechuraba funciona como dos comunas en una: los pasajes y blocks de pocos pisos de La Pincoya y El Barrero por un lado, y los condominios de casas de Pedro Fontova, El Carmen y Santa Marta más las torres de Ciudad Empresarial por otro, todos al pie de los cerros y sin un hospital dentro de la comuna.",
        referencias: "cerca de Vespucio Norte, el Túnel San Cristóbal y los ejes Av. Recoleta y Av. Pedro Fontova",
        llegada: "habitualmente el mismo día o al día siguiente, con hora fija coordinada según la agenda",
    },
    {
        nombre: "Conchalí",
        slug: "conchali",
        provincia: "Santiago",
        zona: "norte",
        cobertura: "full",
        descripcion: "Kinesiología a domicilio en Conchalí: el kinesiólogo llega con camilla y equipo a tu casa, block o condominio, de Vivaceta Barón a El Cortijo. Evaluación inicial gratuita y boleta reembolsable en Isapre y seguros complementarios según tu plan.",
        caracteristicas: [
            "Cobertura en los 7 barrios de Conchalí, de Vivaceta Barón y Juanita Aguirre hasta El Cortijo y Vespucio Norte",
            "Sesiones de alrededor de 60 minutos en casa, block o condominio: el equipo es portátil y sube a mano cuando no hay ascensor",
            "Evaluación inicial gratuita y presencial, en tu casa",
            "Atención de lunes a domingo, con hora fija coordinada por WhatsApp al +56 9 9967 9593",
            "Boleta de honorarios electrónica, reembolsable en Isapre y en seguros complementarios según la cobertura de tu plan",
            "Servicio particular e independiente: sin convenio con hospitales, clínicas ni isapres",
        ],
        sectores: [
            "Vivaceta Barón",
            "El Cortijo",
            "Juanita Aguirre",
            "Vespucio Norte",
            "Balneario",
            "Población La Palmilla",
            "Villa Las Bandurrias",
            "Condominio La Ciudadela",
        ],
        contexto: "Conchalí es chica, plana y completamente urbanizada: 10,7 km² donde conviven pasajes de casas pareadas, blocks de vivienda social sin ascensor y condominios nuevos, así que lo que define la sesión no es la distancia sino el acceso a la puerta.",
        referencias: "cerca de Av. Independencia, Av. Pedro Fontova y el Metro Línea 3",
        llegada: "habitualmente el mismo día o al día siguiente, con hora fija acordada de antemano",
    },
    {
        nombre: "Recoleta",
        slug: "recoleta",
        provincia: "Santiago",
        zona: "centro",
        cobertura: "full",
        descripcion: "Kinesiología a domicilio en Recoleta, de Patronato a Zapadores: adultos mayores, personas operadas y pacientes neurológicos, respiratorios y traumatológicos. Evaluación inicial gratuita.",
        caracteristicas: [
            "Cobertura de sur a norte siguiendo Av. Recoleta y la Línea 2, de Patronato a Zapadores, Dorsal y el borde de El Salto",
            "En los blocks sin ascensor del sector norte, los peldaños del edificio pasan a ser parte del entrenamiento cuando el caso lo permite",
            "En las casas de un piso de Valdivieso y Einstein el pasillo largo sirve para entrenar la marcha sin salir a la calle",
            "Horas acordadas fuera del peak de carga y descarga en Patronato y La Vega, donde estacionar es difícil",
            "Atención de lunes a domingo, coordinada por WhatsApp al +56 9 9967 9593",
        ],
        sectores: [
            "Patronato",
            "La Vega Central",
            "Cerro Blanco",
            "Einstein",
            "Valdivieso",
            "Quinta Bella",
            "Lo Aránguiz",
            "Zapadores",
        ],
        contexto: "Recoleta se ordena por un solo eje: Av. Recoleta y la Línea 2 la cruzan de sur a norte, con el Mapocho cerrándola abajo y el cerro San Cristóbal por el oriente, así que con nombrar la estación más cercana ya queda ubicado un domicilio. Su red pública es de atención primaria, con CESFAM y urgencias SAPU o SAR, mientras el hospital de referencia queda cruzando el límite poniente.",
        referencias: "cerca de Av. Recoleta, Av. Dorsal y las estaciones Cerro Blanco, Einstein y Zapadores de la Línea 2",
        llegada: "el mismo día en la mayoría de los casos, salvo en el sector sur, donde la hora se acuerda fuera del peak de carga y descarga de La Vega",
    },
    {
        nombre: "Independencia",
        slug: "independencia",
        provincia: "Santiago",
        zona: "centro",
        cobertura: "full",
        descripcion: "Kinesiología a domicilio en Independencia: el kinesiólogo llega a tu casa en La Chimba, la Juan Antonio Ríos, Los Castaños o el barrio de los hospitales. Evaluación inicial gratuita y atención de lunes a domingo.",
        caracteristicas: [
            "Cobertura en toda la comuna de Independencia, de La Chimba al borde de Av. Einstein",
            "El kinesiólogo sube con camilla plegable y equipamiento portátil a blocks sin ascensor, cités y casas de pasaje",
            "Evaluación inicial gratuita, con revisión de tus indicaciones médicas si vienes saliendo de alta",
            "Hora coordinada de lunes a domingo, incluidos los horarios en que la familia recién vuelve del trabajo",
            "Llegamos por el eje de Av. Independencia y la Línea 3, y también por Vivaceta, Av. La Paz o la Costanera Norte según tu sector",
            "Servicio particular, sin convenio con hospitales, clínicas ni isapres, con boleta de honorarios electrónica para pedir reembolso en tu Isapre o seguro complementario, según tu plan",
        ],
        sectores: [
            "La Chimba",
            "Barrio Av. Independencia",
            "Población Juan Antonio Ríos",
            "Zona Típica Los Castaños",
            "Barrio Vivaceta",
            "Plaza Chacabuco",
            "Hipódromo Chile",
            "Barrio de los hospitales / Av. La Paz",
        ],
        contexto: "Independencia es el polo hospitalario del norte de Santiago: mucha gente recibe el alta a pocas cuadras de su casa y tiene que seguir la rehabilitación en un cité, una casa antigua de pasaje o un block sin ascensor.",
        referencias: "cerca de Av. Independencia, Av. La Paz y las estaciones Hospitales y Plaza Chacabuco de la Línea 3",
        llegada: "el mismo día o al día siguiente, según la agenda",
    },
    {
        nombre: "Cerro Navia",
        slug: "cerro-navia",
        provincia: "Santiago",
        zona: "poniente",
        cobertura: "full",
        descripcion: "Kinesiología a domicilio en Cerro Navia: atendemos Herminda de la Victoria, Sara Gajardo, Las Viñitas, El Montijo y el borde del Mapocho, con sesiones en casas de pasaje y en departamentos sin ascensor. Evaluación inicial gratuita, de lunes a domingo, con boleta de honorarios electrónica para reembolso en tu Isapre o seguro complementario.",
        caracteristicas: [
            "Cobertura en Herminda de la Victoria, Sara Gajardo, Las Viñitas, El Montijo y el borde del Mapocho",
            "Sesiones en casas de pasaje y en blocks de tres a cinco pisos sin ascensor",
            "Continuamos en tu casa el plan indicado al alta hospitalaria, con tu epicrisis a la vista",
            "Confirmamos por teléfono el punto exacto de llegada cuando el auto no entra al pasaje",
            "Evaluación inicial gratuita, de lunes a domingo",
            "Servicio particular con boleta de honorarios electrónica para reembolso en Isapre o seguro complementario",
        ],
        sectores: [
            "Herminda de la Victoria",
            "Sara Gajardo",
            "Las Viñitas",
            "Población Alianza",
            "El Montijo",
            "Villa Las Parras",
            "Sector Lo Amor",
            "Sector Mapocho Norte",
        ],
        contexto: "Pese a su nombre, Cerro Navia es plana: se vive sobre todo en casas de uno o dos pisos ampliadas por las propias familias y en blocks sin ascensor, muchas veces en pasajes interiores donde el auto no siempre entra. Al no haber Metro dentro de la comuna ni casi oferta de kinesiología particular cerca, rehabilitarse en casa evita cruzar Santiago en micro.",
        referencias: "cerca de Av. José Joaquín Pérez, el eje San Pablo y el borde del río Mapocho",
        llegada: "dentro de 24 horas en la mayoría de los casos, confirmando por teléfono el punto exacto de llegada",
    },
    {
        nombre: "Renca",
        slug: "renca",
        provincia: "Santiago",
        zona: "norte",
        cobertura: "full",
        descripcion: "Kinesiología a domicilio en Renca: sesiones de alrededor de 60 minutos en tu casa, de lunes a domingo, en Huamachuco, Bicentenario, el sector Balmaceda, El Montijo y el borde del Mapocho. La evaluación inicial es gratuita y el plan parte de las indicaciones de tu médico.",
        caracteristicas: [
            "Cobertura a ambos lados del Cerro Renca, incluidos los sectores a los que hay que llegar rodeándolo",
            "Sesiones de alrededor de 60 minutos en tu domicilio, de lunes a domingo, con el horario acordado por WhatsApp al +56 9 9967 9593",
            "Camilla plegable y equipo portátil, pensados para pasajes angostos, antejardines chicos y escaleras de blocks sin ascensor",
            "Evaluación inicial gratuita: el plan se arma con tu epicrisis y las indicaciones de tu médico tratante",
            "Servicio particular con boleta de honorarios electrónica, reembolsable en tu Isapre o seguro complementario según la cobertura de tu plan",
            "Sin convenio con los CESFAM, el SAR ni el Hospital Félix Bulnes: los nombramos solo como referencia de urgencia o de alta",
        ],
        sectores: [
            "Huamachuco",
            "Bicentenario",
            "Sector Balmaceda / Plaza Mayor",
            "El Montijo",
            "Cerro Renca",
            "Villa José Cardín",
            "Población Óscar Bonilla",
            "Borde Mapocho / Av. Domingo Santa María",
        ],
        contexto: "Renca se ordena en torno al Cerro Renca y al eje Balmaceda, con barrios de autoconstrucción, pasajes angostos y blocks de pocos pisos donde entrar con camilla al domicilio suele ser más simple que sacar al paciente de la casa. Como no hay hospital dentro de la comuna, cada control o sesión fuera de casa significa salir, y eso es justo lo que la atención domiciliaria evita.",
        referencias: "cerca de Av. José Manuel Balmaceda, la Plaza Mayor y el Parque El Montijo, con el Cerro Renca como referencia visual y el río Mapocho por el borde sur",
        llegada: "el mismo día o al día siguiente",
    },
    {
        nombre: "Lo Prado",
        slug: "lo-prado",
        provincia: "Santiago",
        zona: "poniente",
        cobertura: "full",
        descripcion: "Kinesiología a domicilio en Lo Prado: Población Lautaro, Villa Ecuador, Jardín Lo Prado, Santa Anita y todo el eje de Av. San Pablo, con sesiones en tu casa de lunes a domingo.",
        caracteristicas: [
            "Cobertura en las villas y pasajes de toda la comuna, de Población Lautaro a Las Rejas Norte",
            "Al agendar conviene indicar el pasaje y una referencia: en las calles interiores el auto suele quedar a media cuadra de la reja",
            "Camilla y equipamiento portátil que entra por accesos a nivel de calle, sin depender de ascensor",
            "En los conjuntos de departamentos de pocos pisos, avísanos el piso antes de la visita",
            "Sesiones de alrededor de 60 minutos, de lunes a domingo, con hora acordada",
            "Servicio particular sin convenio con hospitales ni clínicas: el plan se arma con tu epicrisis y la indicación de tu médico",
        ],
        sectores: [
            "Población Lautaro",
            "Blanqueado",
            "Jardín Lo Prado",
            "Parque Residencial Alameda",
            "Villa Ecuador",
            "Villa Kennedy",
            "Santa Anita",
            "Las Rejas Norte",
        ],
        contexto: "Lo Prado es una comuna compacta y sin pendientes, hecha de villas de vivienda baja y pasajes interiores angostos, donde el kinesiólogo suele entrar con camilla a nivel de calle. Su red de salud es de atención primaria, así que la rehabilitación después de una hospitalización casi siempre hay que resolverla fuera de la comuna.",
        referencias: "cerca de Av. San Pablo y Las Rejas Norte, junto a las estaciones Lo Prado y San Pablo (combinación Líneas 1 y 5)",
        llegada: "habitualmente el mismo día o dentro de 24 horas, con hora acordada",
    },
    {
        nombre: "Pedro Aguirre Cerda",
        slug: "pedro-aguirre-cerda",
        provincia: "Santiago",
        zona: "sur",
        cobertura: "full",
        descripcion: "Kinesiología a domicilio en Pedro Aguirre Cerda, con evaluación inicial gratuita y sesiones en tu casa, en La Victoria, Dávila, Villa Sur o Lo Valledor Norte. Atendemos de lunes a domingo y entregamos boleta de honorarios electrónica para tu Isapre o seguro complementario.",
        caracteristicas: [
            "Cobertura en toda la comuna, incluidos los pasajes interiores de La Victoria, Dávila y Villa Sur",
            "Sesiones de alrededor de 60 minutos, de lunes a domingo, con hora fija acordada contigo",
            "Evaluación inicial gratuita: el kinesiólogo revisa la casa, los accesos y tus indicaciones médicas",
            "El kinesiólogo llega con camilla y equipamiento portátil; si tu dirección es de pasaje, conviene dar una referencia de esquina o el nombre de la villa o unidad vecinal",
            "Servicio particular con boleta de honorarios electrónica, reembolsable en tu Isapre o seguro complementario según tu plan",
            "Sin convenio con hospitales, CESFAM ni isapres: trabajamos con la epicrisis y las indicaciones que te entregaron",
        ],
        sectores: [
            "Población La Victoria",
            "Población Dávila",
            "Lo Valledor Norte",
            "Villa Sur",
            "Los Maitenes",
            "Villa Los Aromos",
            "Núcleo Ochagavía",
            "Parque André Jarlán",
        ],
        contexto: "Pedro Aguirre Cerda es una comuna chica y plana, de poblaciones levantadas hace décadas, donde buena parte de las direcciones son de pasaje interior y el auto no siempre llega hasta la puerta. Que el kinesiólogo entre caminando con su equipo evita que el paciente tenga que salir de la comuna para cada sesión.",
        referencias: "cerca de la Autopista Central, Av. Carlos Valdovinos y las estaciones Lo Valledor y Presidente Pedro Aguirre Cerda de la Línea 6",
        llegada: "coordinamos la primera visita con hora fija, habitualmente dentro de 24 horas",
    },
    {
        nombre: "Lo Espejo",
        slug: "lo-espejo",
        provincia: "Santiago",
        zona: "sur",
        cobertura: "full",
        descripcion: "Kinesiología a domicilio en Lo Espejo: sesiones en tu casa en José María Caro, Santa Adriana, Lo Valledor y el resto de la comuna, con evaluación inicial gratuita y atención de lunes a domingo.",
        caracteristicas: [
            "Cobertura en José María Caro, Santa Adriana, Clara Estrella, Lo Valledor, Villa Sur, Lo Sierra y Pueblo Lo Espejo",
            "Acceso pensado para el pasaje: coordinamos dónde estacionar y por qué puerta entrar con la camilla y el equipo",
            "Casas a nivel de calle y blocks de baja altura sin ascensor: el escalón de entrada y la solera entran en la evaluación",
            "Horarios de mañana y de tarde-noche, y también sábado y domingo, para cuando hay alguien en casa que pueda acompañar",
            "Evaluación inicial gratuita a domicilio, con tu epicrisis y las indicaciones médicas a la vista",
            "Servicio particular con boleta de honorarios electrónica, reembolsable en tu Isapre o seguro complementario según tu plan",
        ],
        sectores: [
            "Población José María Caro",
            "Población Santa Adriana",
            "Población Clara Estrella",
            "Población Lo Valledor",
            "Villa Sur",
            "Población Lo Sierra",
            "Pueblo Lo Espejo",
            "Villa Las Palmeras",
        ],
        contexto: "En Lo Espejo el acceso a las casas suele ser a nivel de calle, pero lo que complica llegar no es el piso sino el pasaje: veredas angostas, soleras altas y autos estacionados a ambos lados. Predominan las viviendas de uno o dos pisos y hay blocks de baja altura sin ascensor, así que el kinesiólogo llega con camilla y equipo hasta la puerta y el trabajo parte por ese recorrido real.",
        referencias: "cerca de Av. Central Cardenal Raúl Silva Henríquez, Américo Vespucio Sur y la estación Lo Espejo del Tren Nos",
        llegada: "dentro de 24 horas en la mayoría de los casos",
    },
    {
        nombre: "Cerrillos",
        slug: "cerrillos",
        provincia: "Santiago",
        zona: "poniente",
        cobertura: "full",
        descripcion: "Kinesiología a domicilio en Cerrillos, de Lo Errázuriz a Ciudad Parque Bicentenario: el kinesiólogo llega con camilla y equipo portátil, aunque el edificio no tenga ascensor. Sesiones de unos 60 minutos, de lunes a domingo, con evaluación inicial gratuita y boleta de honorarios electrónica reembolsable según la cobertura de tu isapre o seguro complementario.",
        caracteristicas: [
            "Cobertura de punta a punta de la comuna: Ciudad Parque Bicentenario, Lo Errázuriz, Villa Los Cerrillos, Villa México, Villa Suiza, Los Presidentes de Chile, Buzeta y Oreste Plath",
            "El kinesiólogo sube con camilla y equipo portátil a los blocks de cuatro o cinco pisos sin ascensor de la trama antigua",
            "En condominios de Ciudad Parque Bicentenario dejamos avisado en conserjería el nombre y la hora, y resolvemos antes el acceso cuando no hay estacionamiento de visita",
            "Sesión adaptada a departamentos de metraje acotado: bastan un par de metros despejados y una silla firme",
            "Llegada por Américo Vespucio o la Autopista Central, con hora fijada considerando el tránsito de camiones de Camino a Melipilla",
            "Evaluación inicial gratuita para definir objetivos y frecuencia antes de contratar un plan, de lunes a domingo",
        ],
        sectores: [
            "Ciudad Parque Bicentenario",
            "Lo Errázuriz",
            "Villa Los Cerrillos",
            "Población Los Presidentes de Chile",
            "Villa México",
            "Buzeta",
            "Barrio Industrial Cerrillos",
            "Entorno de Mallplaza Oeste",
        ],
        contexto: "En Cerrillos conviven dos tramas muy distintas: la antigua, de villas y poblaciones como Lo Errázuriz, Villa México o Los Presidentes de Chile, con casas bajas y blocks de cuatro o cinco pisos; y la nueva de Ciudad Parque Bicentenario, levantada sobre el terreno del ex aeropuerto, con edificios con ascensor, conserjería y departamentos de metraje acotado. La sesión se arma distinto en cada una.",
        referencias: "cerca de Av. Américo Vespucio y Mallplaza Oeste, la estación Cerrillos de la Línea 6 y el eje de Camino a Melipilla",
        llegada: "el mismo día o al día siguiente, coordinando la hora contigo",
    },
    {
        nombre: "Quinta Normal",
        slug: "quinta-normal",
        provincia: "Santiago",
        zona: "centro",
        cobertura: "full",
        descripcion: "Kinesiología a domicilio en Quinta Normal: sesiones de unos 60 minutos en tu casa, en el Tropezón, Lo Franco, Garín, Blanqueado y el resto de la comuna. Evaluación inicial gratuita, de lunes a domingo.",
        caracteristicas: [
            "Cobertura en Tropezón, Lo Franco, Garín, Blanqueado, Estación Yungay, Barrio Argentina y Lourdes",
            "Casas que abren directo a la vereda, sin antejardín: trabajamos con el peldaño de entrada, la reja, los pasillos angostos y la escalera interior",
            "Calles de trazado antiguo con autos a ambos lados: el kinesiólogo estaciona donde alcanza y entra a pie con la camilla, que es portátil",
            "Sesiones de unos 60 minutos, de lunes a domingo, con hora coordinada contigo",
            "Si vives cerca del eje Mapocho-Radal, acordamos la llegada con margen por las calles intervenidas y los desvíos de las obras de la futura Línea 7",
            "Evaluación inicial gratuita y boleta de honorarios electrónica para pedir reembolso en tu Isapre o seguro complementario, según tu plan",
        ],
        sectores: [
            "Barrio Tropezón",
            "Lo Franco",
            "Garín",
            "Blanqueado",
            "Barrio Lourdes",
            "Estación Yungay",
            "Barrio Argentina",
            "Población Simón Bolívar",
        ],
        contexto: "Quinta Normal se recorre por calles de trazado antiguo y angosto, con autos estacionados a ambos lados y viviendas de uno y dos pisos que abren directo a la vereda, sin antejardín. Ninguno de los recintos con urgencia 24 horas queda dentro de la comuna, así que resolver la rehabilitación en la propia casa evita salir dos o tres veces por semana justo cuando cuesta moverse.",
        referencias: "cerca de Av. Carrascal, San Pablo y el eje Mapocho, con las estaciones Blanqueado y Gruta de Lourdes de la Línea 5",
        llegada: "el mismo día o al día siguiente en la mayoría de los casos, con hora coordinada",
    },
    {
        nombre: "Estación Central",
        slug: "estacion-central",
        provincia: "Santiago",
        zona: "centro",
        cobertura: "full",
        descripcion: "Kinesiología a domicilio en Estación Central: sesiones de unos 60 minutos en Villa Francia, Villa Portales, Los Nogales, Las Rejas y el eje Alameda, de lunes a domingo, con evaluación inicial gratuita.",
        caracteristicas: [
            "Cobertura de punta a punta de la comuna: del eje Alameda al sector poniente de San José de Chuchunco",
            "Llegamos a pie hasta la puerta, incluidos blocks sin ascensor y departamentos con entrada por pasarela",
            "El kinesiólogo trae el equipamiento portátil y arma la sesión con el espacio disponible: camilla si cabe y, si no, sobre una cama firme o una silla",
            "Sesiones de unos 60 minutos, de lunes a domingo, con el bloque horario acordado antes",
            "Evaluación inicial gratuita en tu casa, con revisión de la epicrisis si vienes saliendo de un alta",
            "Servicio particular con boleta de honorarios electrónica, reembolsable en tu isapre o seguro complementario según tu plan",
        ],
        sectores: [
            "Villa Francia",
            "Villa Portales",
            "Población Robert Kennedy",
            "Los Nogales",
            "San José de Chuchunco",
            "Las Rejas",
            "Sector Ecuador",
            "Barrio Estación Central",
        ],
        contexto: "En pocas cuadras Estación Central pasa de las torres del eje Alameda a blocks sin ascensor, pasarelas de Villa Portales y casas de un piso con patio: el kinesiólogo llega con equipamiento portátil y arma la sesión con el espacio que haya, sin que nadie tenga que salir de su casa para rehabilitarse.",
        referencias: "cerca de la Alameda, Av. Las Rejas y las estaciones de Línea 1 Ecuador, Universidad de Santiago y Estación Central",
        llegada: "habitualmente el mismo día o al día siguiente, con el bloque horario confirmado contigo porque estacionar cerca de la Alameda toma tiempo",
    },
    {
        nombre: "San Miguel",
        slug: "san-miguel",
        provincia: "Santiago",
        zona: "centro",
        cobertura: "full",
        descripcion: "Kinesiología a domicilio en San Miguel: sesiones de alrededor de 60 minutos en tu casa o departamento, en El Llano, Lo Vial, Ciudad del Niño y Departamental. Evaluación inicial gratuita y atención de lunes a domingo.",
        caracteristicas: [
            "Cobertura en el eje Gran Avenida dentro de la comuna, desde El Llano Subercaseaux hasta Departamental y Ciudad del Niño",
            "Comuna plana y compacta: el kinesiólogo llega en auto o por la Línea 2 del Metro, y el horario se acuerda contigo al agendar",
            "Sesiones de alrededor de 60 minutos en casa, departamento o block, con camilla y equipamiento portátil",
            "Continuidad del tratamiento tras un alta hospitalaria, siguiendo la epicrisis y las indicaciones médicas que traes",
            "Boleta de honorarios electrónica: es una atención particular y el reembolso depende de la cobertura de tu plan de Isapre o seguro complementario",
            "Evaluación inicial gratuita y atención de lunes a domingo, coordinada al WhatsApp +56 9 9967 9593",
        ],
        sectores: [
            "El Llano Subercaseaux",
            "Lo Vial",
            "Ciudad del Niño",
            "Departamental",
            "Barrio Atacama",
            "Barrio Gauss",
            "Población Silva Vildósola",
            "Los Molineros",
        ],
        contexto: "San Miguel tiene dos hospitales públicos grandes dentro de sus propios límites, así que muchos vecinos reciben el alta a pocas cuadras de su casa y necesitan seguir la rehabilitación ahí mismo, sin volver a cruzar la ciudad.",
        referencias: "cerca de Gran Avenida, El Llano Subercaseaux y las estaciones Lo Vial, Departamental y Ciudad del Niño de la Línea 2",
        llegada: "habitualmente el mismo día o al día siguiente",
    },
    {
        nombre: "La Granja",
        slug: "la-granja",
        provincia: "Santiago",
        zona: "sur",
        cobertura: "full",
        descripcion: "Kinesiología a domicilio en La Granja: el kinesiólogo entra por Vespucio o Santa Rosa y llega con camilla y equipamiento hasta Yungay, San Gregorio, Joao Goulart o Granja Sur. La rehabilitación se hace en tu casa, sin salir de la comuna.",
        caracteristicas: [
            "Cobertura en las poblaciones y villas de toda la comuna, del eje San Gregorio al borde de Vespucio.",
            "Ubicamos tu casa por el nombre de la población o villa y una referencia cercana: acá esa dirección funciona mejor que la calle sola.",
            "Ingreso habitual por Américo Vespucio o Av. Santa Rosa, y también por las estaciones La Granja y Santa Rosa de la Línea 4A.",
            "Distancias cortas dentro de la comuna: hay horarios temprano, al mediodía o después del trabajo, incluidos sábado y domingo.",
            "El plan puede incluir tus recorridos reales: la vuelta a la manzana, el trayecto al paradero o los tramos de ciclovía de la comuna.",
            "Servicio particular e independiente: no tenemos convenio con hospitales, clínicas ni isapres.",
        ],
        sectores: [
            "Población Yungay",
            "Población Malaquías Concha",
            "Población San Gregorio",
            "Villa Brasil",
            "Población Joao Goulart",
            "Villa Ovalle",
            "Villa Los Pensamientos",
            "Sector Padre Esteban Gumucio",
        ],
        contexto: "La Granja se lee por barrios: 69 poblaciones y villas repartidas en 17 unidades vecinales, donde la referencia útil para ubicar una casa es el nombre de la población y el pasaje, más que el número de la calle. Es una comuna chica y de trazado llano, que se cruza de punta a punta en pocos minutos, así que el kinesiólogo puede tomar una hora temprano en Yungay y otra al final del día en Granja Sur sin que la agenda se caiga.",
        referencias: "cerca de Américo Vespucio, Av. Santa Rosa y las estaciones La Granja y Santa Rosa de la Línea 4A",
        llegada: "habitualmente dentro de 24 horas, con hora fija acordada contigo",
    },
    {
        nombre: "La Cisterna",
        slug: "la-cisterna",
        provincia: "Santiago",
        zona: "sur",
        cobertura: "full",
        descripcion: "Kinesiología a domicilio en La Cisterna: adulto mayor, post operatorio, respiratorio, neurológico y traumatológico en tu propia casa, con evaluación inicial gratuita y atención de lunes a domingo.",
        caracteristicas: [
            "Cobertura en toda La Cisterna, desde el límite de Av. Lo Ovalle hasta El Parrón",
            "Nos ubicas por paradero de Gran Avenida o por la Estación Intermodal y coordinamos desde ahí",
            "Acceso resuelto en casa con antejardín y en los edificios nuevos junto al Metro: preguntamos por el piso antes de ir",
            "Evaluación inicial gratuita en tu domicilio, de lunes a domingo, en sesiones de alrededor de 60 minutos",
            "Boleta de honorarios electrónica para reembolso en Isapre o seguro complementario, según tu plan",
            "Servicio particular e independiente: sin convenio con clínicas ni hospitales",
        ],
        sectores: [
            "El Parrón",
            "Santa Anselma",
            "Nueva España",
            "Villa Italia",
            "Brisas del Maipo",
            "Fernández Albano",
            "Paradero 22 / Templo San Juan Bosco",
            "Estación Intermodal La Cisterna",
        ],
        contexto: "La Cisterna cabe en unos 10 km² de llano, sin cerros ni subidas, y con un trazado de manzanas regulares que la distingue de los pasajes de otras poblaciones del sector. Para una visita domiciliaria eso se traduce en direcciones fáciles de ubicar y casi siempre en un lugar donde estacionar frente a la puerta, aunque el kinesiólogo llegue cargando camilla y equipo.",
        referencias: "cerca de Gran Avenida José Miguel Carrera, Av. El Parrón, Av. Fernández Albano y la Estación Intermodal La Cisterna",
        llegada: "el mismo día o al día siguiente, según la agenda",
    },
    {
        nombre: "San Ramón",
        slug: "san-ramon",
        provincia: "Santiago",
        zona: "sur",
        cobertura: "full",
        descripcion: "Kinesiología a domicilio en San Ramón: sesiones de alrededor de 60 minutos en tu casa o departamento, en La Bandera, Los Prunos, Villa Casas Blancas y el resto de la comuna, con evaluación inicial gratuita.",
        caracteristicas: [
            "Atendemos de lunes a domingo en toda la comuna, de La Bandera a Barrio Modelo.",
            "Evaluación inicial gratuita: si después decides no seguir, no pagas nada.",
            "Servicio particular con boleta de honorarios electrónica, reembolsable en tu isapre o seguro complementario según la cobertura de tu plan.",
            "Trabajamos sobre los accesos reales de tu casa: peldaños hechos por la propia familia, umbrales altos y escaleras de conjuntos sin ascensor.",
            "Sin cerros ni pendientes en la comuna: cuando el kinesiólogo lo estima seguro, la caminata de la sesión sale a la vereda o al Parque La Bandera.",
            "La primera visita se coordina por WhatsApp al +56 9 9967 9593 y queda con hora fija, habitualmente para el día siguiente.",
        ],
        sectores: [
            "La Bandera",
            "Los Prunos",
            "Villa Casas Blancas",
            "General Körner",
            "Villa La Cultura",
            "Villa Manuel Rengifo",
            "Nueva Paraguay",
            "Barrio Modelo",
        ],
        contexto: "San Ramón es la comuna más pequeña de Chile en superficie y una de las más densas: casi todo queda a pocas cuadras, pero muchas casas están en pasajes angostos de acceso vehicular limitado, donde el último tramo se hace a pie.",
        referencias: "cerca de Vespucio Sur y Av. Santa Rosa, entre el eje La Bandera y Av. Ossa, donde está la municipalidad",
        llegada: "con hora fija, habitualmente al día siguiente",
    },
    {
        nombre: "Colina",
        slug: "colina",
        provincia: "Chacabuco",
        zona: "norte",
        cobertura: "hub",
        descripcion: "Atendemos en el casco urbano de Colina y Esmeralda, en los condominios de Chicureo, Piedra Roja y Chamisero, y en sectores rurales como Liray o Las Canteras, en una comuna del valle de Chacabuco sin red de Metro. Evaluación inicial gratuita y sesiones de alrededor de 60 minutos, de lunes a domingo.",
        caracteristicas: [
            "Cubrimos el casco urbano y Esmeralda, los condominios de Chicureo, Piedra Roja y Chamisero, y sectores rurales como Las Canteras, Liray y Peldehue.",
            "Cada visita se agenda con hora acordada de antemano, porque llegar depende de la Autopista Los Libertadores, la Ruta 5 Norte o la Autopista Nororiente.",
            "En condominios cerrados pedimos dejar avisado el ingreso en portería antes de la hora, para no perder la sesión en el acceso.",
            "En direcciones rurales trabajamos con el kilómetro y una referencia del camino interior, más un teléfono de contacto para ubicar la parcela.",
            "En Colina el obstáculo suele ser el peldaño del antejardín o la escalera de la casa, no un ascensor: la evaluación parte por ahí.",
            "Atendemos de lunes a domingo, algo útil cuando la visita depende de que alguien de la casa esté con el auto disponible.",
        ],
        sectores: [
            "Centro de Colina (Plaza de Armas)",
            "Chicureo",
            "Piedra Roja",
            "Chamisero",
            "Esmeralda",
            "Las Canteras",
            "Liray",
            "Peldehue",
        ],
        contexto: "Colina mezcla tres realidades en un mismo territorio: el casco urbano en torno a la Plaza de Armas, los condominios del eje Chicureo–Chamisero y los sectores rurales del valle de Chacabuco. Cada uno cambia cómo se entra a la casa y cómo se planifica la visita.",
        referencias: "cerca de la Autopista Los Libertadores, la Carretera General San Martín y el Camino Chicureo–Colina",
        llegada: "coordinamos la visita según agenda, habitualmente dentro de 24 a 48 horas",
    },
    {
        nombre: "El Bosque",
        slug: "el-bosque",
        provincia: "Santiago",
        zona: "sur",
        cobertura: "full",
        descripcion: "Kinesiología a domicilio en El Bosque: atención particular en tu casa, de Santa Elena a Lo Blanco, con evaluación inicial gratuita y sesiones de lunes a domingo.",
        caracteristicas: [
            "Cobertura a ambos lados de la Base Aérea, desde Santa Elena y Lo Espina hasta Lo Blanco y Lo Martínez",
            "Llegamos por Gran Avenida y por las estaciones El Bosque, Observatorio y Copa Lo Martínez de la Línea 2, con hora fija",
            "Entrenamos los trayectos que de verdad haces: el paradero de Gran Avenida, la escalera de tu estación o el camino al CESFAM",
            "Continuidad tras un alta del Hospital El Pino, cruzando el límite comunal, siguiendo las indicaciones de tu médico tratante",
            "Evaluación inicial gratuita antes de comprometer cualquier plan",
            "Servicio particular con boleta de honorarios electrónica para presentar en tu isapre o seguro complementario",
        ],
        sectores: [
            "Población El Bosque",
            "Santa Elena",
            "Los Sauces",
            "Lo Espina",
            "Santa Laura",
            "Cóndores de Chile",
            "Barrio Lo Blanco",
            "Sector Lo Martínez",
        ],
        contexto: "El Bosque es una comuna compacta, ordenada de norte a sur por Gran Avenida, donde la Base Aérea ocupa una porción grande del territorio y obliga a rodearla para pasar de un sector a otro. Su hospital de referencia, El Pino, queda cruzando el límite comunal y tiene estación propia en la Línea 2: el regreso a casa tras el alta es corto, y es ahí donde puede seguir la rehabilitación.",
        referencias: "cerca de Gran Avenida José Miguel Carrera, Lo Blanco y las estaciones El Bosque y Copa Lo Martínez de la Línea 2",
        llegada: "el mismo día o al día siguiente",
    },
    {
        nombre: "Lampa",
        slug: "lampa",
        provincia: "Chacabuco",
        zona: "norte",
        cobertura: "hub",
        descripcion: "Kinesiología a domicilio en Lampa: el kinesiólogo llega a tu casa, condominio o parcela con camilla y equipamiento portátil, y las visitas se agrupan en un mismo recorrido para no depender de viajes sueltos desde Santiago.",
        caracteristicas: [
            "Cobertura en el pueblo de Lampa, Valle Grande, Larapinta, Batuco y Estación Colina",
            "También llegamos a las parcelas de Chicauma y al entorno del humedal de Batuco, con acceso por camino interior",
            "Visitas agrupadas en el eje Camino Lampa (G-16), sin depender de un viaje suelto desde Santiago por cada sesión",
            "Coordinación con hora fija según agenda, habitualmente dentro de 24 a 48 horas",
            "Evaluación inicial gratuita antes de armar el plan",
            "Servicio particular con boleta de honorarios electrónica, reembolsable en tu Isapre o seguro complementario, según tu plan",
        ],
        sectores: [
            "Lampa centro (el pueblo)",
            "Valle Grande",
            "Larapinta",
            "Batuco",
            "Estación Colina",
            "Chicauma",
            "Sol de Septiembre",
        ],
        contexto: "Lampa funciona como localidades separadas por kilómetros de camino: el pueblo, Valle Grande y Larapinta, Batuco, Estación Colina y las parcelas de Chicauma. Como la red de salud propia es solo atención primaria, casi cualquier rehabilitación obliga a salir de la comuna, y llevar al kinesiólogo a la casa evita repetir ese viaje varias veces por semana.",
        referencias: "cerca del Camino Lampa (G-16) entre el pueblo, Batuco y Estación Colina, y de la Ruta 5 Norte por el enlace Américo Vespucio Norte",
        llegada: "según agenda, habitualmente dentro de 24 a 48 horas",
    },
    {
        nombre: "Til Til",
        slug: "tiltil",
        provincia: "Chacabuco",
        zona: "norte",
        cobertura: "hub",
        descripcion: "Visitas kinesiológicas en el domicilio, en las localidades dispersas de Til Til: sesiones de alrededor de 60 minutos, de lunes a domingo, con hora acordada por sector y evaluación inicial gratuita.",
        caracteristicas: [
            "Cobertura en el casco urbano de Til Til, Huertos Familiares, Polpaico, Rungue, Montenegro y sectores de cerro como Caleu",
            "Hora acordada por sector: al ser una comuna extensa y de caminos rurales, la agenda se arma por zona para llegar puntual",
            "Sesiones de alrededor de 60 minutos en tu casa, de lunes a domingo",
            "Kinesiólogos titulados que llegan con camilla y equipamiento portátil, sin que tengas que trasladar al paciente",
            "Evaluación inicial gratuita, con revisión de la epicrisis y las indicaciones médicas si vienes saliendo de un alta",
            "Servicio particular con boleta de honorarios electrónica, reembolsable en tu Isapre o seguro complementario según tu plan",
        ],
        sectores: [
            "Pueblo de Tiltil (casco urbano)",
            "Huertos Familiares",
            "Polpaico",
            "Estación Polpaico",
            "Rungue",
            "Montenegro",
            "Caleu",
            "Huechún",
        ],
        contexto: "Til Til es la comuna más alejada del Gran Santiago por el norte de la Región Metropolitana, a unos 55 km del centro de Santiago, y sus localidades están separadas entre sí por kilómetros de camino rural. Cuando el control o la rehabilitación quedan fuera de la comuna, el viaje es por la Ruta 5 Norte; llevar la sesión a la casa evita ese traslado y deja el tratamiento donde la persona se mueve cada día.",
        referencias: "cerca de la Ruta 5 Norte, Av. Arturo Prat en el pueblo y el camino que une Polpaico con Huertos Familiares",
        llegada: "coordinamos la visita según agenda, habitualmente dentro de 24 a 48 horas",
    },
    {
        nombre: "Padre Hurtado",
        slug: "padre-hurtado",
        provincia: "Talagante",
        zona: "poniente",
        cobertura: "hub",
        descripcion: "Kinesiología a domicilio en Padre Hurtado, provincia de Talagante: el kinesiólogo llega con camilla y equipamiento a tu casa o parcela. Evaluación inicial gratuita y boleta de honorarios reembolsable en tu Isapre o seguro complementario según tu plan.",
        caracteristicas: [
            "Cobertura en el eje San Alberto Hurtado y en los barrios nuevos levantados hacia la Autopista del Sol",
            "También llegamos a parcelas y caminos interiores del sector rural: indícanos un kilómetro o una referencia junto a la dirección",
            "La hora se coordina con anticipación por la distancia desde Santiago, con agenda de lunes a domingo",
            "Evaluación inicial gratuita y sesiones de alrededor de 60 minutos",
            "Boleta de honorarios electrónica, reembolsable en tu Isapre o seguro complementario según la cobertura de tu plan",
            "Si vienes saliendo del Hospital de Talagante o del Hospital El Carmen, el plan parte del informe de alta y de la pauta médica",
        ],
        sectores: [
            "Padre Hurtado centro (eje San Alberto Hurtado)",
            "Santa Rosa de Chena",
            "La Esperanza",
            "Santa Mónica",
            "El Trebal",
            "El Curato",
            "Sector poniente hacia la Cuesta Barriga",
            "Barrios nuevos junto a la Autopista del Sol",
        ],
        contexto: "En Padre Hurtado no hay hospital: el CESFAM y su SAPU son municipales y la urgencia de alta complejidad queda a unos 25 km, en Talagante o en Maipú, por la Ruta 78. Atenderte en casa te ahorra ese viaje, y si vives en el sector rural basta con darnos un kilómetro o una referencia junto a la dirección para ubicar la parcela.",
        referencias: "cerca del eje San Alberto Hurtado (ex Camino a Melipilla), la Ruta 78 y el Camino Lonquén",
        llegada: "coordinamos la visita según agenda, habitualmente dentro de 24 a 48 horas",
    },
    {
        nombre: "Peñaflor",
        slug: "penaflor",
        provincia: "Talagante",
        zona: "poniente",
        cobertura: "hub",
        descripcion: "Kinesiología a domicilio en Peñaflor y Malloco: el kinesiólogo llega a tu casa con camilla y equipamiento, con evaluación inicial gratuita y atención de lunes a domingo. Servicio particular, con boleta de honorarios electrónica reembolsable en tu Isapre o seguro complementario según tu plan.",
        caracteristicas: [
            "Cobertura en Peñaflor centro, Malloco, El Trapiche, Las Praderas y el sector de parcelas de los bordes de la comuna",
            "Hora fija acordada con anticipación: coordinamos la visita según agenda, habitualmente dentro de 24 a 48 horas",
            "El kinesiólogo llega con camilla y equipamiento portátil: en las casas con patio y living amplio suele sobrar espacio para la sesión",
            "Evaluación inicial gratuita y sesiones de alrededor de 60 minutos, de lunes a domingo",
            "Servicio particular con boleta de honorarios electrónica, reembolsable en tu Isapre o seguro complementario según la cobertura de tu plan",
            "Si vives en una parcela o en una dirección sin numeración clara, coordinamos por WhatsApp una referencia (la Plaza de Malloco o el cerro La Virgen) antes de la visita",
        ],
        sectores: [
            "Peñaflor centro (Plaza de Armas)",
            "Malloco",
            "El Trapiche",
            "Pelvín",
            "Las Praderas (eje Av. Troncal)",
            "Villa La Foresta",
            "Villa Rialto",
            "Miraflores",
        ],
        contexto: "Peñaflor queda en la Provincia de Talagante, a unos 37 km al suroeste del centro de Santiago, así que salir a control después de un alta significa un viaje por la Autopista del Sol o el Camino a Melipilla justo cuando moverse cuesta más. Las casas con patio y el casco urbano sin pendientes dejan espacio real para trabajar con camilla y equipamiento.",
        referencias: "cerca de Av. Vicuña Mackenna, la Plaza de Armas y la Plaza de Malloco, con el eje Av. Troncal y acceso por la Autopista del Sol o el Camino a Melipilla",
        llegada: "coordinamos la visita según agenda, habitualmente dentro de 24 a 48 horas",
    },
    {
        nombre: "Talagante",
        slug: "talagante",
        provincia: "Talagante",
        zona: "poniente",
        cobertura: "hub",
        descripcion: "Kinesiología a domicilio en Talagante, en el casco urbano y en el sector rural de Lonquén y El Pino Viejo. Evaluación inicial gratuita, sesiones de alrededor de 60 minutos y atención de lunes a domingo.",
        caracteristicas: [
            "Casco urbano, villas y sector rural de Lonquén",
            "Entrada directa desde la calle, sin ascensores",
            "En parcelas acordamos antes un punto de referencia",
            "Evaluación inicial gratuita",
            "Sesiones de ~60 minutos, de lunes a domingo",
            "Boleta reembolsable en tu Isapre o seguro complementario",
        ],
        sectores: [
            "Centro de Talagante",
            "Sector Claretianos",
            "Villa Los Presidentes",
            "Sector de Pasaje Quemchi",
            "Eje Esmeralda–Francisco Chacón",
            "Lonquén",
            "El Pino Viejo",
        ],
        contexto: "Talagante es capital de su provincia y queda a unos 35 km al suroeste del centro de Santiago por la Ruta 78, la Autopista del Sol. Se vive a nivel de calle: el kinesiólogo estaciona frente a la casa y entra directo, sin hall ni conserjería. Hacia Lonquén y El Pino Viejo el panorama es rural, con parcelas y caminos interiores.",
        referencias: "cerca de Av. Bernardo O'Higgins, la calle Balmaceda del hospital y la salida a la Ruta 78",
        llegada: "coordinamos la visita según agenda, habitualmente dentro de 24 a 48 horas",
    },
    {
        nombre: "Isla de Maipo",
        slug: "isla-de-maipo",
        provincia: "Talagante",
        zona: "poniente",
        cobertura: "hub",
        descripcion: "Kinesiología a domicilio en Isla de Maipo: el kinesiólogo llega a tu casa o parcela, tanto en Isla Centro y La Islita como en los sectores rurales de la comuna. Evaluación inicial gratuita, de lunes a domingo.",
        caracteristicas: [
            "Atendemos los dos núcleos urbanos, Isla Centro y La Islita, y también los sectores rurales como Naltahua, Arquería o La Villita.",
            "Llegamos por la Autopista del Sol o el Camino a Lonquén; la hora se acuerda con anticipación y te avisamos por WhatsApp si el camino atrasa la llegada.",
            "Sesiones de alrededor de 60 minutos, de lunes a domingo, con día y hora convenidos de antemano, porque el kinesiólogo viaja hasta la comuna y no atiende por orden de llegada.",
            "Nos adaptamos al acceso de cada vivienda: el peldaño de la entrada, el trecho que separa la casa del camino y los pasillos angostos de las villas de Isla Centro y La Islita.",
            "La evaluación inicial es gratuita y se hace igual en una casa de Villa Bicentenario que en una parcela de Naltahua; ahí revisamos tu epicrisis e indicaciones médicas antes de armar el plan.",
            "Servicio particular con boleta de honorarios electrónica: el reembolso en tu Isapre o seguro complementario se tramita habitualmente en línea, según la cobertura de tu plan, sin que tengas que salir de la comuna.",
        ],
        sectores: [
            "Isla Centro",
            "La Islita",
            "San Antonio de Naltahua",
            "Lonquén",
            "Puntilla de Lonquén",
            "La Villita",
            "Arquería",
            "Villa Bicentenario",
        ],
        contexto: "Isla de Maipo es una comuna de valle donde la vivienda es casi toda de uno o dos pisos y buena parte del territorio es rural: parcelas, viñas y caminos interiores. Rehabilitarse fuera obliga a salir a la carretera, así que viaja el kinesiólogo y no el paciente.",
        referencias: "cerca de la salida Talagante–Isla de Maipo de la Autopista del Sol, el Camino a Lonquén y el eje de Av. Jaime Guzmán",
        llegada: "coordinamos la visita según agenda, habitualmente dentro de 24 a 48 horas",
    },
    {
        nombre: "Buin",
        slug: "buin",
        provincia: "Maipo",
        zona: "sur",
        cobertura: "hub",
        descripcion: "Kinesiólogo a domicilio en Buin, Provincia de Maipo: rehabilitación en tu casa siguiendo las indicaciones de tu médico tratante, con camilla y equipamiento propios. Sesiones de alrededor de 60 minutos, de lunes a domingo.",
        caracteristicas: [
            "Al agendar basta con indicar la localidad —Buin centro, Alto Jahuel, Linderos, Maipo o Viluco— porque las distancias dentro de la comuna son largas",
            "Llegamos también a direcciones sin numeración a la vista en caminos rurales: coordinas un cruce o una referencia por WhatsApp al +56 9 9967 9593",
            "La visita se coordina según agenda, habitualmente dentro de 24 a 48 horas, de lunes a domingo",
            "Terreno plano y accesos a nivel de calle: la camilla y el equipamiento entran sin ascensores ni escaleras de edificio",
            "Planes mensuales Essential $160.000 (4 sesiones) y Premium $350.000 (10 sesiones, $35.000 cada una); Elite a consultar, con evaluación inicial gratuita antes de contratar",
            "Servicio particular con boleta de honorarios electrónica, reembolsable en Isapre y seguros complementarios según la cobertura de tu plan",
        ],
        sectores: [
            "Buin centro",
            "Alto Jahuel",
            "Linderos",
            "Maipo",
            "Valdivia de Paine",
            "Viluco",
            "El Recurso",
            "Campusano",
        ],
        contexto: "Buin queda a unos 35 kilómetros al sur de Santiago y es tan extensa que dos direcciones \"en Buin\" pueden estar a varios kilómetros una de otra: por eso la visita se coordina por localidad —el centro, Alto Jahuel, Linderos o los sectores de parcelas— y no por comuna.",
        referencias: "cerca de la Ruta 5 Sur, la Plaza de Armas de Buin y las estaciones Buin y Linderos del Metrotren",
        llegada: "coordinamos la visita según agenda, habitualmente dentro de 24 a 48 horas",
    },
    {
        nombre: "El Monte",
        slug: "el-monte",
        provincia: "Talagante",
        zona: "poniente",
        cobertura: "hub",
        descripcion: "Kinesiología a domicilio en El Monte, provincia de Talagante: sesiones de unos 60 minutos en tu casa, desde el casco urbano hasta El Paico, Lo Chacón y Chiñigüe. Evaluación inicial gratuita y atención particular con boleta de honorarios electrónica.",
        caracteristicas: [
            "Cubrimos el casco urbano de El Monte y también los sectores de parcelas: El Paico, El Paico Alto, Lo Chacón y Chiñigüe.",
            "En los caminos rurales pedimos una referencia (un cruce, un portón o el kilómetro), porque muchas direcciones no se dan por número.",
            "Valle plano entre el Mapocho y el Maipo: se entra con camilla y equipo sin depender de ascensor, aunque las distancias entre sectores son reales.",
            "Llegamos por la Autopista del Sol y el enlace El Paico; las visitas seguidas se agendan por sector, no por hora.",
            "No hay Metro en la comuna ni en la provincia de Talagante: la sesión en casa te ahorra el viaje en auto o en bus interurbano.",
            "Atendemos de lunes a domingo; por la distancia desde Santiago la primera visita se coordina, habitualmente dentro de 24 a 48 horas.",
        ],
        sectores: [
            "El Monte centro",
            "El Paico",
            "El Paico Alto",
            "Lo Chacón",
            "Chiñigüe",
            "El Tejar",
            "Villa El Alba",
            "Santa Isabel",
        ],
        contexto: "El Monte queda a unos 45 km al suroeste de Santiago y no tiene Metro, ni en la comuna ni en el resto de la provincia de Talagante: toda terapia fuera de casa se hace en auto o en bus interurbano. Por eso aquí la visita domiciliaria ahorra un traslado completo, no solo una hora de espera.",
        referencias: "cerca de Plaza Independencia, el eje de Av. Libertadores y el enlace El Paico de la Autopista del Sol",
        llegada: "según agenda, habitualmente dentro de 24 a 48 horas",
    },
    {
        nombre: "Pirque",
        slug: "pirque",
        provincia: "Cordillera",
        zona: "sur",
        cobertura: "hub",
        descripcion: "Kinesiología a domicilio en Pirque: Pirque centro, La Puntilla, El Principal, Santa Rita, San Vicente y Río Clarillo. Sesiones de unos 60 minutos en tu casa o parcela, con evaluación inicial gratuita y hora fija acordada.",
        caracteristicas: [
            "Cobertura en Pirque centro, La Puntilla, El Principal, Santa Rita, San Vicente y Río Clarillo",
            "Llegamos por los caminos interiores hasta el portón de la casa o la parcela, y la camilla se descarga ahí",
            "Hora fija acordada por WhatsApp al +56 9 9967 9593, porque entre una dirección y la siguiente hay caminos largos",
            "La evaluación inicial gratuita incluye revisar el acceso desde el camino hasta la puerta; las sesiones duran unos 60 minutos",
            "Atención de lunes a domingo, con hora acordada",
            "Boleta de honorarios electrónica, reembolsable en tu Isapre o seguro complementario según tu plan",
        ],
        sectores: [
            "Pirque centro",
            "La Puntilla",
            "El Principal",
            "Santa Rita",
            "San Vicente",
            "Río Clarillo",
        ],
        contexto: "En Pirque las direcciones están separadas por caminos rurales y entrar o salir obliga a pasar por el puente de Av. Concha y Toro, el cuello de botella del acceso desde Puente Alto. Cada sesión de rehabilitación fuera de la comuna significa cruzar ese puente y volver por los mismos caminos; en casa, en cambio, la hora queda fijada y el kinesiólogo llega hasta las parcelas y los sectores del piedemonte.",
        referencias: "cerca de Av. Concha y Toro, el puente sobre el río Maipo, Av. Virginia Subercaseaux y el camino a Río Clarillo",
        llegada: "coordinamos la visita según agenda, habitualmente dentro de 24 a 48 horas",
    },
    {
        nombre: "San José de Maipo",
        slug: "san-jose-de-maipo",
        provincia: "Cordillera",
        zona: "sur",
        cobertura: "hub",
        descripcion: "Estamos llevando la kinesiología a domicilio al Cajón del Maipo: sesiones de unos 60 minutos en tu casa del pueblo, La Obra, El Canelo o San Alfonso, con evaluación inicial gratuita y boleta reembolsable en Isapre según tu plan. Confirmamos tu localidad antes de agendar.",
        caracteristicas: [
            "Cobertura en ampliación al Cajón del Maipo: confirmamos tu localidad y, con agenda disponible, la visita queda habitualmente dentro de 24 a 48 horas",
            "Sesiones de unos 60 minutos en tu casa, sin bajar por la Ruta G-25 hasta un centro de Santiago",
            "Equipamiento portátil que entra por antejardines, terrazas y accesos en pendiente, rara vez con ascensores de por medio",
            "Evaluación inicial gratuita, con revisión de epicrisis e indicaciones médicas si vienes de un alta",
            "Boleta de honorarios electrónica, reembolsable en Isapre y seguros complementarios según la cobertura de tu plan",
            "Atención de lunes a domingo, con hora acordada por WhatsApp al +56 9 9967 9593",
        ],
        sectores: [
            "San José de Maipo (pueblo)",
            "La Obra",
            "Las Vertientes",
            "El Canelo",
            "El Manzano",
            "Guayacán",
            "El Melocotón",
            "San Alfonso",
        ],
        contexto: "En San José de Maipo el camino es uno solo: la Ruta G-25 ordena la comuna de punta a punta, así que la localidad manda sobre la agenda. No es lo mismo una hora en el pueblo que en El Melocotón o San Alfonso, y por eso confirmamos hasta dónde llegamos antes de fijar día y hora.",
        referencias: "sobre la Ruta G-25 (Camino al Volcán), entre el cruce de La Obra y San Alfonso",
        llegada: "estamos ampliando la cobertura al Cajón: confirmamos disponibilidad para tu localidad y, cuando hay agenda, coordinamos la visita dentro de 24 a 48 horas",
    },
    {
        nombre: "Paine",
        slug: "paine",
        provincia: "Maipo",
        zona: "sur",
        cobertura: "hub",
        descripcion: "Kinesiología a domicilio en Paine, desde Paine centro y la localidad de Hospital hasta Champa, Huelquén, Chada y Aculeo. Evaluación inicial gratuita en tu propia casa, con camilla y equipamiento portátil.",
        caracteristicas: [
            "Cobertura en Paine centro y en las localidades rurales: la localidad de Hospital, Champa, Huelquén, Chada, Pintué y Aculeo",
            "Hora fija acordada con anticipación, porque de Paine centro a Aculeo o a Rangue hay varios kilómetros de camino",
            "Pedimos una referencia del camino cuando el domicilio no tiene número visible, algo habitual en los accesos interiores del sector rural",
            "Camilla y equipamiento portátil que habitualmente entran a nivel, sin ascensor de por medio",
            "Te ahorra el viaje a Santiago por la Ruta 5 Sur o en el tren cada vez que toca sesión",
            "Evaluación inicial gratuita en tu domicilio y sesiones de alrededor de 60 minutos, de lunes a domingo",
        ],
        sectores: [
            "Paine centro",
            "Hospital (localidad)",
            "Champa",
            "Huelquén",
            "Chada",
            "Aculeo",
            "Pintué",
            "Culitrín",
        ],
        contexto: "Paine mezcla un centro urbano compacto con localidades rurales separadas por varios kilómetros, y su urgencia hospitalaria más cercana queda fuera de la comuna. Atenderse en casa evita viajes largos justo cuando moverse cuesta más.",
        referencias: "cerca de la Ruta 5 Sur, el eje Av. General Baquedano y las estaciones Paine y Hospital del tren a Rancagua",
        llegada: "coordinamos la visita según agenda, habitualmente dentro de 24 a 48 horas",
    },
    {
        nombre: "Calera de Tango",
        slug: "calera-de-tango",
        provincia: "Maipo",
        zona: "sur",
        cobertura: "hub",
        descripcion: "Kinesiología a domicilio en Calera de Tango: del pueblo y el eje de Avenida Calera de Tango a San Ignacio, Bajos de San Agustín y el Camino a Lonquén. Servicio particular con boleta de honorarios electrónica, sin salir de la comuna por cada sesión.",
        caracteristicas: [
            "Cobertura en el pueblo, San Ignacio, Bajos de San Agustín y el eje del Camino a Lonquén",
            "Coordinamos la visita según agenda, habitualmente dentro de 24 a 48 horas",
            "Hora fija acordada con anticipación, porque la comuna es rural y extensa",
            "Conviene enviar la ubicación y avisar quién abre el portón: hay direcciones por kilómetro de camino",
            "Evaluación inicial gratuita, de lunes a domingo",
            "Servicio particular con boleta de honorarios electrónica, reembolsable en tu Isapre o seguro complementario según tu plan",
        ],
        sectores: [
            "San Ignacio",
            "Bajos de San Agustín",
            "Calera de Tango pueblo",
            "Camino a Lonquén",
            "Faldeos del cerro Chena",
            "Faldeos de los cerros de Lonquén",
        ],
        contexto: "Calera de Tango es mayoritariamente rural: muchos vecinos viven en parcelas y en sectores en crecimiento como San Ignacio o Bajos de San Agustín, donde la dirección se explica por kilómetro de camino y portón antes que por número. A unos 26 km del centro de Santiago y sin estación de metro en la comuna, bajar a rehabilitarse fuera implica un viaje completo por cada sesión.",
        referencias: "cerca de Avenida Calera de Tango, la Hacienda, el Camino a Lonquén y los faldeos del cerro Chena",
        llegada: "coordinamos la visita según agenda, habitualmente dentro de 24 a 48 horas",
    },
    {
        nombre: "Melipilla",
        slug: "melipilla",
        provincia: "Melipilla",
        zona: "poniente",
        cobertura: "hub",
        descripcion: "Kinesiología a domicilio en Melipilla: casco urbano, Pomaire, Bollenar, Mallarauco, Codigua y Puangue. Evaluación inicial gratuita y sesiones en tu casa, de lunes a domingo.",
        caracteristicas: [
            "Cobertura en el casco urbano de Melipilla y en localidades rurales como Pomaire, Bollenar, Mallarauco, Codigua y Puangue",
            "Predominan las casas de uno o dos pisos y las villas de acceso plano; si vives en un edificio, el kinesiólogo sube igual con camilla y equipamiento",
            "Si tu dirección se da por kilómetro o por una referencia del camino, acordamos antes el punto de llegada y quién abre el portón",
            "Hora acordada con anticipación y sesiones de alrededor de 60 minutos, para que la distancia entre localidades no te deje esperando",
            "Servicio particular con boleta de honorarios electrónica, reembolsable en tu Isapre o seguro complementario según tu plan",
            "Tras un alta en el Hospital San José de Melipilla o en un centro fuera de la comuna, seguimos las indicaciones escritas de tu médico tratante",
        ],
        sectores: [
            "Pomaire",
            "Bollenar",
            "Mallarauco",
            "Codigua",
            "Puangue",
            "Villa El Portal",
            "Padre Demetrio",
            "Cerro Chololo",
        ],
        contexto: "Melipilla es una comuna extensa: alrededor de 1.345 km² en los que una ciudad compacta de casas bajas convive con localidades y parcelas repartidas por el valle. Según dónde vivas, llegar al centro cívico puede ser un trayecto largo por caminos interiores, y eso pesa cuando recién te operaron o caminar te cuesta.",
        referencias: "cerca de la Ruta 78, la salida a Pomaire y el eje de Avenida Silva Chávez",
        llegada: "coordinamos la visita según agenda, habitualmente dentro de 24 a 48 horas",
    },
    {
        nombre: "Curacaví",
        slug: "curacavi",
        provincia: "Melipilla",
        zona: "poniente",
        cobertura: "hub",
        descripcion: "Kinesiología a domicilio en Curacaví, tanto en el casco urbano del valle como en los sectores de parcelas y caminos interiores. En esos sectores muchas direcciones se explican por referencias y no por numeración, así que la ruta se confirma al agendar.",
        caracteristicas: [
            "Estamos ampliando la cobertura a Curacaví: escríbenos y confirmamos disponibilidad para tu dirección, en el casco urbano o en los sectores rurales",
            "Visitas coordinadas por agenda, habitualmente dentro de 24 a 48 horas según la dirección y el acceso",
            "Kinesiólogos titulados con camilla y equipamiento portátil, pensado para casas de un piso y para sectores a los que se llega por caminos interiores",
            "Evaluación inicial gratuita en tu casa: sirve además para ver el espacio y el acceso antes de llevar la camilla a un sector rural",
            "Boleta de honorarios electrónica que llega a tu correo, reembolsable en tu Isapre y en seguros complementarios según tu plan",
            "Atención particular de lunes a domingo, incluido fin de semana",
        ],
        sectores: [
            "Centro de Curacaví",
            "Cuyuncaví",
            "Cerrillos",
            "Miraflores",
            "Lo Águila",
            "Patagüilla",
            "La Laguna",
            "Los Panguiles",
        ],
        contexto: "Curacaví está a unos 46 kilómetros de Santiago por la Ruta 68, en un valle rodeado de cuestas, y buena parte de sus vecinos vive en parcelas y sectores rurales lejos del casco urbano. Rehabilitarse en un centro obliga a sumar el viaje al tratamiento, así que recibir la sesión en la propia casa resuelve las dos cosas a la vez.",
        referencias: "cerca de la Plaza Presidente Balmaceda, el eje de Avenida Ambrosio O'Higgins y los accesos Curacaví Oriente y Poniente de la Ruta 68",
        llegada: "coordinamos la visita según agenda, habitualmente dentro de 24 a 48 horas",
    },
    {
        nombre: "San Pedro",
        slug: "san-pedro",
        provincia: "Melipilla",
        zona: "poniente",
        cobertura: "hub",
        descripcion: "Kinesiología a domicilio en San Pedro, la comuna rural de la provincia de Melipilla: el kinesiólogo llega a la casa o la parcela, en el pueblo y en sectores dispersos como Loica, Longovilo y El Yali.",
        caracteristicas: [
            "Atención en el pueblo de San Pedro y en sectores rurales como Loica Arriba, Loica Abajo, Longovilo, Corneche y El Yali",
            "Casas de un piso en sitios y parcelas: en la mayoría de los casos la camilla y el equipamiento entran sin escaleras ni ascensores",
            "Coordinamos por WhatsApp la referencia del portón y el estado del camino interior antes de la visita",
            "Coordinamos la visita según agenda, habitualmente dentro de 24 a 48 horas, con hora acordada para tu sector",
            "Horarios acordados con holgura: cuando hay faenas con tránsito alternado en la Ruta 66, los tiempos de llegada pueden alargarse",
            "Sectores distantes entre sí: si en Loica, Longovilo o El Yali la señal de celular es débil, deja un segundo número de contacto al agendar",
        ],
        sectores: [
            "San Pedro centro",
            "Loica Arriba",
            "Loica Abajo",
            "Longovilo",
            "Corneche",
            "El Prado",
            "Las Pataguas",
            "El Yali",
        ],
        contexto: "San Pedro es la única comuna 100% rural de la Región Metropolitana: sus sectores están dispersos entre el valle del estero El Yali y los faldeos de la cordillera de la Costa, y la ciudad más cercana con hospital es Melipilla, a 44 kilómetros del pueblo. Recibir las sesiones en la casa evita ese traslado justo cuando más cuesta moverse.",
        referencias: "junto a la Ruta 66, la Carretera de la Fruta, con Avenida Hermosilla como calle principal del pueblo y la Ruta G-60 como salida hacia Melipilla",
        llegada: "coordinamos la visita según agenda, habitualmente dentro de 24 a 48 horas, con hora acordada para tu sector",
    },
    {
        nombre: "Alhué",
        slug: "alhue",
        provincia: "Melipilla",
        zona: "poniente",
        cobertura: "hub",
        descripcion: "Kinesiología a domicilio para Alhué: Villa Alhué, Hacienda Alhué y los sectores interiores quedan a unos 139 km de Santiago, así que confirmamos disponibilidad por WhatsApp antes de agendar. Evaluación inicial gratuita y boleta de honorarios reembolsable en Isapre según tu plan.",
        caracteristicas: [
            "Sesiones en casas de un piso, parcelas y caseríos, con acceso por caminos interiores de ripio",
            "Cobertura fuera de nuestro radio habitual: te confirmamos por WhatsApp antes de agendar, sin compromiso",
            "Sesiones de alrededor de 60 minutos, con camilla y equipamiento portátil que se traslada en vehículo",
            "Visita coordinada con anticipación y con una ventana horaria acordada, por los kilómetros de camino interior",
            "Evaluación inicial gratuita y atención de lunes a domingo",
            "Boleta de honorarios electrónica, reembolsable en Isapre y seguros complementarios según la cobertura de tu plan",
        ],
        sectores: [
            "Villa Alhué",
            "Hacienda Alhué",
            "El Asiento",
            "Pichi",
            "Talamí",
            "Polulo",
            "Carén",
            "Loncha",
        ],
        contexto: "Alhué es la comuna menos poblada de la Región Metropolitana y una de las más rurales: sus caseríos se reparten por 845 km² de cerros y quebradas de la Cordillera de la Costa, y la red de salud local es de baja complejidad, así que los cuadros que necesitan mayor resolución se derivan fuera de la comuna, hacia Melipilla.",
        referencias: "en torno a la Ruta G-60 y la Ruta G-660, con el casco de Villa Alhué entre las calles 21 de Mayo y Dieciocho de Septiembre",
        llegada: "solo previa confirmación de cobertura, acordando contigo día y hora según agenda",
    },
    {
        nombre: "María Pinto",
        slug: "maria-pinto",
        provincia: "Melipilla",
        zona: "poniente",
        cobertura: "hub",
        descripcion: "Kinesiología a domicilio en María Pinto, provincia de Melipilla: atención en el pueblo y en los sectores rurales, con evaluación inicial gratuita y boleta de honorarios reembolsable en tu Isapre o seguro complementario.",
        caracteristicas: [
            "Atención en el pueblo y en las localidades rurales de la comuna",
            "Visita con hora convenida, porque los sectores quedan distantes entre sí",
            "Camilla y equipamiento portátil hasta casas, parcelas y viviendas en camino rural",
            "Sesiones de alrededor de 60 minutos, de lunes a domingo",
            "Evaluación inicial gratuita en tu casa, sin trasladar al paciente por caminos rurales",
            "Boleta de honorarios electrónica para pedir reembolso en Isapre o seguro complementario",
        ],
        sectores: [
            "María Pinto centro (pueblo)",
            "Los Rulos",
            "Villa Santa Luisa",
            "Santa Emilia",
            "Chorombo Alto",
            "Ibacache Alto",
            "Las Mercedes",
            "Lo Ovalle",
        ],
        contexto: "En María Pinto la gente vive repartida en 23 localidades separadas por lomas, quebradas y caminos rurales, y el transporte hacia el centro cívico o fuera de la comuna es limitado. El kinesiólogo llega hasta la casa con hora convenida, así el tratamiento no depende de conseguir traslado.",
        referencias: "cerca de Av. Francisco Costabal, en el centro cívico, donde la ruta G-734 une la G-730 con la G-76",
        llegada: "coordinamos la visita según agenda, habitualmente dentro de 24 a 48 horas",
    },
]

export function getComuna(slug: string) {
    return comunas.find((c) => c.slug === slug)
}

/** Comunas con matriz completa de paginas por especialidad. */
export const comunasFull = comunas.filter((c) => c.cobertura === "full")

/**
 * Comunas para enlazar desde una pagina local: primero las de la misma zona,
 * despues el resto, para que el enlazado interno sea geograficamente coherente
 * y no un muro de 50 enlaces iguales en todas las paginas.
 */
export function comunasVecinas(slug: string, limite = 11, soloFull = true) {
    const base = soloFull ? comunasFull : comunas
    const actual = getComuna(slug)
    const resto = base.filter((c) => c.slug !== slug)
    if (!actual) return resto.slice(0, limite)
    const mismas = resto.filter((c) => c.zona === actual.zona)
    const otras = resto.filter((c) => c.zona !== actual.zona)
    return [...mismas, ...otras].slice(0, limite)
}
